books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.list_books),
    url(r'^read/(?P<ind>[0-9]*)/(?P<part>.*)/?$', views.read_book),
    url(r'^read/(?P<tr_wrt>[^/]*)/(?P<tr_titl>[^/]*)/(?P<ind>[0-9]*)/(?P<part>.*)/?$', views.read_book),
    url(r'^get_file/(?P<ind>[0-9]*)/?$', views.get_file),
    url(r'^wrt/(?P<id_wrt>[0-9]*)/?$', views.list_books),
    url(r'^wrt/(?P<tr_wrt>[^/]*)/(?P<id_wrt>[0-9]*)/?$', views.list_books),
    url(r'^subj/?$', views.list_subj),
    url(r'^subj/(?P<id_subj>[0-9]*)/?$', views.list_books),
    url(r'^subj/(?P<tr_subj>[^/]*)/(?P<id_subj>[0-9]*)/?$', views.list_books),
    url(r'^add/?$', views.add_book),
    url(r'^del/(?P<id>[0-9]*)/?$', views.delete_book),
    url(r'^edit/(?P<id>[0-9]*)/?$', views.edit_book),
    url(r'^edit_wrt/(?P<id>[0-9]*)/?$', views.edit_wrt),
    url(r'^user/(?P<id>[0-9]*)/?$', views.user_profile),
]

django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

djangoappengine/conf/project_template/project_name/urls.py
from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

urls.py
from django.conf.urls import include, url
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', include('news.urls')),
    url(r'^about/', 'fotos.views.index'),
    url(r'^av/(?P<id>[0-9]*)/?$', 'fotos.views.get_avatar'),
    url(r'^news/', include('news.urls')),
    url(r'^guestbook$', RedirectView.as_view(url='/posts/')), # old name
    url(r'^guestbook/(?P<p>.*)', RedirectView.as_view(url='/posts/%(p)s')),
    url(r'^posts/', include('posts.urls')),
    url(r'^photos/', include('fotos.urls')),
    url(r'^fotos/', include('fotos.urls')),    
    url(r'^songs/', include('songs.urls')),
    url(r'^books/', include('books.urls')),
#    url(r'^upload/', include('upload.urls')),

    url(r'^signup/?$', 'fotos.views.create_new_user'),
    url(r'^login/?$', 'django.contrib.auth.views.login',
        {'authentication_form': AuthenticationForm,
        'template_name': 'login.html',}),
    url(r'^logout/?$', 'django.contrib.auth.views.logout',
        {'redirect_field_name': 'b',}),
    url(r'^captcha/', include('captcha.urls')),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class Writer(models.Model):
    writer = models.CharField(max_length=150, db_index=True, verbose_name=_('writer'))
    content = models.TextField(null=True, blank=True, verbose_name=_('content'))
    count = models.IntegerField()

class Subject(models.Model):
    subject = models.CharField(max_length=150, db_index=True, verbose_name=_('subject'))
    count = models.IntegerField()

class Book(models.Model):
    class Meta:
        unique_together = ('writer', 'title') # not worked for gae
    writer = models.ForeignKey(Writer, db_index=True)
    title = models.CharField(max_length=150, verbose_name=_('title'))
    subject = models.ForeignKey(Subject, db_index=True)
    index = models.IntegerField() # unique writer+title
    content = models.TextField(verbose_name=_('content'))
    author = models.ForeignKey(User, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=_('date'))
    file = models.FileField(null=True, blank=True, upload_to='files', verbose_name=_('file'))

books/forms.py
from django import forms
from django.utils.translation import ugettext as _
from books.models import *

class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['writer', 'subject', 'author', 'date', 'index', 'index2', 'thumb_url']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 20}),
        }

class AddWrtForm(forms.ModelForm):
    class Meta:
        model = Writer
        exclude = ['count']
        widgets = {
            'writer': forms.TextInput(attrs={'class': 'formtext'}),
        }

class AddWrtFormAll(forms.ModelForm):
    class Meta:
        model = Writer
        widgets = {
            'writer': forms.TextInput(attrs={'class': 'formtext', 'readonly':True}),
        }

class AddSubjForm(forms.ModelForm):
    class Meta:
        model = Subject
        exclude = ['count']

class SearchForm(forms.Form):
    wrt = forms.CharField(max_length=100, label=_('Search by writer'))
    tit = forms.CharField(max_length=100, label=_('or title'))

books/views.py
#-*- coding: utf-8 -*-

from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.core.exceptions import *
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render_to_response
from django.template.context import RequestContext
from django.template.defaultfilters import truncatewords, striptags, slugify
from django.db.models import Q
from google.appengine.api import images
from google.appengine.ext import blobstore
from books.forms import *
from books.models import *
from templatetags.customfilters import *
from filetransfers.api import prepare_upload
from filetransfers.api import serve_file
from math import ceil
import datetime, re
import zlib, zipfile, base64, mimetypes

def E_OS(text):
    "Convert To Unicode"
    return text.decode('utf-8')

def ZI(s):
    try:
        s=int(s)
        if not s: raise
        else: return s
    except:
        raise Http404

def PageList(request, qst, per_page=5):
    """Return Paginator list."""
    paginator = Paginator(qst, per_page)
    try:    # first page
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:    # last page
        return paginator.page(page)
    except (EmptyPage, InvalidPage):
        return paginator.page(paginator.num_pages) 

def AddWrtListCache(wrt_key, wrt_list):
    cache_list = []
    i = 0
    for wrt in wrt_list:
        i += 1
        cache_list.append({
           'id': wrt.id,
           'counter': i,
           'writer': {'id': wrt.id, 'writer': wrt.writer, 'count': wrt.count},
           'tr_wrt': to_translit(wrt.writer),
           'count': wrt.count })
    cache.add('wrts:' + wrt_key, str(cache_list))

def AddSubjListCache(subj_key, subj_list):
    cache_list = []
    for subj in subj_list:
        cache_list.append({
           'id': subj.id,
           'subject': subj.subject,
           'tr_subj': to_translit(subj.subject),
           'count': subj.count })
    cache.add('subj:' + subj_key, str(cache_list))

def AddBookCache(book, part, content):
    st = re.findall('(\d+)', part)
    if st: npart = int(st[0])
    else : npart = 0
    cache_book = {
        'id': book.id,
        'writer': {'id': book.writer.id, 'writer': book.writer.writer, 'count': book.writer.count},
        'subject': ((hasattr(book, 'subject') and book.subject) and {'id': book.subject.id, 'subject': book.subject.subject, 'count': book.subject.count}) or {},
        'title': book.title,
        'tr_wrt': to_translit(book.writer.writer),
        'tr_subj': to_translit(book.subject.subject),
        'tr_titl': to_translit(book.title),
        'index': book.index,
        'part': part,
        'npart': npart,
        'prev_npart': npart - 1,
        'next_npart': npart + 1,
        'file': ((hasattr(book, 'file') and book.file) and {'name': book.file.name.rsplit('/')[-1]}) or {},
        'content': E_OS(content),
        'author': ((hasattr(book, 'author') and book.author) and {'id': book.author.id, 'username': book.author.username}) or {},
        'date': book.date }
    cache.add('book:' + str(book.index) + '.' + str(part), str(cache_book))
    return cache_book

def AddBookListCache(mkey, book_list, **kw):
    cache_list = []
    dlist = []
    for book in book_list:
        try:
            book.writer
        except:
            continue
        dkey = book.writer.writer + ' ' + book.title
        if not dkey in dlist: 
            # description content
            content = GetBookContent(book, 'content.opf')
            dlist.append(dkey)
            cache_list.append({
               'id': book.id,
               'counter': (kw.get('page_num', 1)-1) * kw.get('per_page', 0) + (len(cache_list)+1),
               'writer': {'id': book.writer.id, 'writer': book.writer.writer, 'count': book.writer.count},
               'subject': {'id': book.subject.id, 'subject': book.subject.subject, 'count': book.subject.count},
               'title': book.title,
               'tr_wrt': to_translit(book.writer.writer),
               'tr_subj': to_translit(book.subject.subject),
               'tr_titl': to_translit(book.title),
               'content': truncatewords(content, 80),
               'index': book.index,
               'date': book.date })
    cache.add('books:' + str(mkey), str(cache_list))

def AddWrtCache(wrt_id, wrt):
    cache_wrt = {
        'id': wrt.id,
        'writer': wrt.writer,
        'tr_wrt': to_translit(wrt.writer),
        'content': wrt.content,
        'count': wrt.count }
    cache.add('wrt:' + str(wrt_id), str(cache_wrt))
    return cache_wrt

def ClearWrtCache(wrt_key):
    cache.delete_many(['wrt:' + str(wrt_key)])

def ClearWrtListCache(wrt_key):
    try:    cache.delete_many(['wrts:.full_list', 'wrts:' + str(wrt_key)])
    except: pass
    ClearSubjListCache()

def ClearSubjListCache():
    cache.delete_many(['subj:.full_list'])

def ClearBookCache(book_ind):
    for book_part in range(0, 100):
        cache.delete_many(['book:' + str(book_ind) + '.' + str(book_part)])

def ClearBookListWrtCache(wrt_id):
    for page_num in range(1, 101):
        cache.delete_many(['books:' + str(wrt_id) + '.' + str(page_num)])
    for page_num in range(1, 101):
        cache.delete_many(['books:.last_update' + '.' + str(page_num)])
    ClearSubjListCache()

def ClearBookListSubjCache(subj_id):
    for page_num in range(1, 101):
        cache.delete_many(['books:.subj' + str(subj_id) + '.' + str(page_num)])
    for page_num in range(1, 101):
        cache.delete_many(['books:.last_update' + '.' + str(page_num)])
    ClearSubjListCache()

# extract content text, image, cover_image from .epub
def GetBookContent(book, part='0'):
    content = ''
    if ((hasattr(book, 'file') and book.file)):
        name = book.file.name.replace("'","''").rsplit('/')[-1]
        for blob in blobstore.BlobInfo.gql("WHERE filename = '%s'"  % (name,)):
            za = zipfile.ZipFile(blob.open())
            # get content from zip archive by name or num part
            for f in za.namelist():
                mpart = re.findall('(\d+)', f)
                try:
                    ft = za.read(f)
                    if ((part.isdigit() and len(mpart) and int(part) == int(mpart[0])) or (part == f) or (part == '0' and f == 'index.xhtml')) and f.startswith('index') and f.endswith('.xhtml'):
                        try:
                            content = re.findall('<body[^>]*>(.*)</body>', ft, re.M | re.S)[0]
                        except:
                            content = ''
                    elif (part == f) and f.startswith('content.opf'):
                        try:
                            title = re.findall('>(.*)</dc:title>', ft)[0]
                            writer = re.findall('>(.*)</dc:creator>', ft)[0]
                            content = re.findall('<dc:description>(.*)</dc:description>', ft, re.M | re.S)
                            if len(content):
                                content = content[0]
                            else:
                                content = writer + ' ' + title
                        except:
                            content = ''
                    elif ((part == f) or part.startswith('cover')) and (f.endswith('.jpg') or f.endswith('.jpeg') or f.endswith('.png')):
                        content = base64.b64encode(ft)
                except:
                    continue
                if content:
                    break
    return content

# increment wrt book count
def IncWrtCount(**kw):
    if kw.get('writer'):
        try:
            form = AddWrtForm(instance=Writer.objects.get(writer=kw['writer']))
            wrt = form.save(commit=False)
            wrt.count += kw.get('count', 1)
            wrt.save(force_update=True)
            if wrt.count < 1:
                ClearWrtListCache(wrt.writer[0])
                wrt.delete()
        except:
            form = AddWrtForm()
            wrt = form.save(commit=False)
            wrt.writer = kw['writer']
            wrt.count = kw.get('count', 1)
            wrt.save()
        return wrt

# increment subject book count
def IncSubjCount(**kw):
    if kw.get('subject'):
        try:
            form = AddSubjForm(instance=Subject.objects.get(subject=kw['subject']))
            subj = form.save(commit=False)
            subj.count += kw.get('count', 1)
            subj.save(force_update=True)
            if subj.count < 1:
                subj.delete()
        except:
            form = AddSubjForm()
            subj = form.save(commit=False)
            subj.subject = kw['subject']
            subj.count = kw.get('count', 1)
            subj.save()
        return subj

# Controllers

def list_books(request, **kw):
    book_count = 0
    wrt_count = 0
    last_count = 0
    search_count = 0
    book_list = []
    wrt_list = []
    subj_list = []
    subject = None
    writer = None
    page_num = ZI(request.GET.get('page', '1'))
    per_page = 10
    page_bottom = (page_num-1)*per_page
    page_top = page_bottom+per_page
    if kw.get('id_wrt'): # filter by wrt
        wrt_id = ZI(kw.get('id_wrt'))
        wrt_key = str(wrt_id) + '.' + str(page_num)
        if not cache.has_key('books:' + wrt_key):
            book_list = Book.objects.filter(writer=wrt_id).order_by('title')[page_bottom:page_top]
            AddBookListCache(wrt_key, book_list, page_num=page_num, per_page=per_page)
        book_list = eval(cache.get('books:' + wrt_key))
        if len(book_list):
            book_count = book_list[0]['writer']['count']
            if not cache.has_key('books:' + wrt_key):

books/templates/add_book.html
{% extends 'base.html' %}
{% load i18n %}
{% load filetransfers %}
{% block description %}{% trans 'Add book' %} {% endblock %}
{% block keywords %}{% trans 'Add book' %}, {% endblock %}
{% block title %}{% trans 'Add book' %} - {% trans 'books' %} - {% endblock %}
{% block pagestyle %}
#id_title { width:100%; }
{% endblock %}
{% block booksclass %}wrap3{% endblock %}
{% block pageheader %}{# trans 'Add book' #}{% endblock %}
{% block content %}

<p class="mtext hspace">Добавляйте свои тексты книг. </p>

<p>
  <form action="{{ upload_url }}" enctype="multipart/form-data" method="post">
  {% render_upload_data upload_data %}
{% if request.user.is_authenticated %}
    <table class="mtext formpost">
      {{ form_wrt }}{{ form }}{{ form_subj }}
      <tr><th/><td><input type="submit" value="{% trans 'Post' %}" /></td></tr>
    </table>
{% else %}
  <p class="mtext hspace">{% trans "Please authorize to add books" %}</p>
{% endif %}
  </form>
</p>

{% endblock %}

books/templates/book.html
{% extends 'base.html' %}
{% load i18n %}
{% load customfilters %}
{% block description %}{{ book.content|strip_anno|striptags|strip_text|truncatewords:"40" }} {% endblock %}
{% block keywords %}{{ book.writer.writer|strans }}, {{ book.title }}, {% trans 'books' %}, {% endblock %}
{% block title %}{{ book.writer.writer|strans }} - {{ book.title }}, {% trans 'books' %} - {% endblock %}
{% block pagestylelink %}
<link rel="stylesheet" href="{{ MEDIA_URL }}css/books/stylesheet.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}css/books/page_styles.css" type="text/css" />
{% endblock %}
{% block pagestyle%}
.lside2 { min-width:200px; max-width:200px; }
{% endblock %}
{% block booksclass %}wrap3{% endblock %}
{% block pagescript %}
{% endblock %}
{% block pageheader %}
{% endblock %}

{% block content %}

<div class="indexlist mtext wrap">
  <form class="search" action="{% url 'books.views.list_books' %}" method="get">{% csrf_token %}
    <a class="nodecor hspaced" href="{% url 'books.views.list_subj' %}">Жанры</a>
    <a class="nodecor hspaced" href="{% url 'books.views.list_books' %}?wrt=*">Авторы</a>
    {{ form }}
    <input class="submit" type="submit" value="Найти" />
  </form>
</div>

<p>
  <h2 class="nomarg"><a class="nodecor" href="{% url 'books.views.list_books' tr_wrt=book.tr_wrt id_wrt=book.writer.id %}"><span class="hspace">{{ book.writer.writer|strans }} </span></a>{{ book.title }}</h2>
</p>

{% if request.user.is_authenticated %}
  {% if book.prev_npart >= 0 %}
    <a href="{% url 'books.views.read_book' ind=book.index part=book.prev_npart %}">
      <div class="wrap cfloat">
        <img src='{{ MEDIA_URL }}img/s_up.png' title="{% trans 'previous' %}" alt="{% trans 'previous' %}" />
      </div>
    </a>
  {% endif %}
{% endif %}

<div class="wrap">
  <dl class="msgtext"><dt>
  {% if book.npart == 0 %}
    <div class="lside2 cfloat">
      <img id="cover-{{ book.title|to_translit }}" title="{{ book.writer.writer }} {{ book.title }}" alt="{{ book.writer.writer }} {{ book.title }}" src="{% url 'books.views.read_book' ind=book.index part='cover.jpeg' %}" width="160px"/><br/>
    </div>
  {% endif %}
    <div class="calibre">{{ book.content|strip_anno|safe }}</div>
  </dt></dl>
  <div class="msgfooter gray">
    {% trans 'Added' %}
    {% if book.author %} 
      <a href="{% url 'books.views.user_profile' id=book.author.id %}">{{ book.author.username }}</a> 
    {% else %}
      {% trans 'An anonymous person' %}
    {% endif %}
    <acronym title="{{ book.date }}">{{ book.date|time_since }}</acronym>
    {% if request.user.is_authenticated and request.user.id == book.author.id or request.user.is_superuser %}
      <a class="nodecor hspace2" href="{% url 'books.views.edit_book' id=book.id %}">{% trans 'Edit' %}</a>
      <a class="nodecor" href="{% url 'books.views.delete_book' id=book.id %}">{% trans 'Delete' %}</a>
    {% endif %}
  </div>
</div>

{% if request.user.is_authenticated %}
  {% if book.next_npart >= 0 %}
    <a href="{% url 'books.views.read_book' ind=book.index part=book.next_npart %}">
      <div class="wrap cfloat">
        <img src='{{ MEDIA_URL }}img/s_down.png' title="{% trans 'next' %}" alt="{% trans 'next' %}" />
      </div>
    </a>
  {% endif %}
{% else %}
  <p class="mtext hspace">{% trans 'Please authorize to get books' %}</p>
{% endif %}

{% endblock %}

books/templates/edit_book.html
{% extends 'base.html' %}
{% load i18n %}
{% load filetransfers %}
{% block description %}{% trans 'Edit book' %} {% endblock %}
{% block keywords %}{% trans 'Edit book' %}, {% endblock %}
{% block title %}{% trans 'Edit book' %} - {% trans 'books' %} - {% endblock %}
{% block pagestyle %}
#id_writer { color: #c8c8c8; }
#id_title { width:100%; }
{% endblock %}
{% block booksclass %}wrap3{% endblock %}
{% block pageheader %}{# trans 'Edit book' #}{% endblock %}
{% block content %}

<p class="mtext hspace">Изменяйте тексты книг.</p>

<p>
  <form action="{{ upload_url }}" enctype="multipart/form-data" method="post">
  {% render_upload_data upload_data %}
{% if request.user.is_authenticated %}
    <table class="mtext formpost">
      {{ form }}
      <tr><th/><td><input type="submit" value="{% trans 'Post' %}" /></td></tr>
    </table>
    <input type="hidden" id="id_id" name="id" value="{{ form.initial.id }}" />
{% else %}
  <p class="mtext hspace">{% trans "Please authorize to edit books" %}</p>
{% endif %}
  </form>
</p>  
  
{% endblock %}

books/templates/edit_wrt.html
{% extends 'base.html' %}
{% load i18n %}
{% load filetransfers %}
{% block description %}{% trans 'Edit writer' %} {% endblock %}
{% block keywords %}{% trans 'Edit writer' %}, {% endblock %}
{% block title %}{% trans 'Edit writer' %} - {% trans 'books' %} - {% endblock %}
{% block pagestyle %}
#id_writer { color: #c8c8c8; }
#id_title { width:100%; }
{% endblock %}
{% block booksclass %}wrap3{% endblock %}
{% block pageheader %}{# trans 'Edit writer' #}{% endblock %}
{% block content %}

<p class="mtext hspace">Править автора. </p>

<p>
  <form action="{{ upload_url }}" enctype="multipart/form-data" method="post">
{% if request.user.is_authenticated %}
    <table class="mtext formpost">
      {{ form }}
      <tr><th/><td><input type="submit" value="{% trans 'Post' %}" /></td></tr>
    </table>
    <input type="hidden" id="id_id" name="id" value="{{ form.initial.id }}" />
{% else %}
  <p class="mtext hspace">{% trans "Please authorize to edit books" %}</p>
{% endif %}
  </form>
</p>

{% endblock %}

books/templates/subj.html
{% extends 'base.html' %}
{% load i18n %}
{% load customfilters %}
{% block description %}Жанры, {% trans 'books' %} {% endblock %}
{% block keywords %}Жанры, {% trans 'books' %}, {% endblock %}
{% block title %}
Жанры - {% trans 'books' %} - {% endblock %}
{% block booksclass %}wrap3{% endblock %}
{% block pageheader %}
{% endblock %}
{% block content %}

<p class="mtext hspace">Список жанров книг:</p>

{% if subjects.object_list %}
  {% for subj in subjects.object_list %}
    <div class="wrap">
      <dl class="msgtext tabl"><dt class="lfloat minw">
        <a class="nodecor" href="{% url 'books.views.list_books' tr_subj=subj.tr_subj id_subj=subj.id %}">
          {{ subj.subject }} </a></dt>
        <dt>&nbsp;<b>{{ subj.count }}</b>&nbsp;</dt>
        <div class="gray smaller">{% trans subj.subject%}</div>
      </dl>
    </div>
  {% endfor %}
{% else %}
  <p class="mtext hspace">{% trans 'No books' %}.</p>
{% endif %}

<p class="mtext hspace">
{% if request.user.is_authenticated %}
  <a href="{% url 'books.views.add_book' %}">{% trans 'Add book' %}</a>
{% else %}
  {% trans 'Please authorize to add books' %}
{% endif %}
</p>

{% endblock %}